### ISSUE TITLE
List of Interactables

### ISSUE THREAD

**Issue by Zamiell** [ReznoRMichael/hollow-knight-completion-check#5]
Hello, and thanks for the fantastic tool, it was just what I needed.

Are there plans to implement lists for geo rocks / interactables?
I want to go through and get everything on my 100% save file.

**Comment by ReznoRMichael** [comment]
There is no way to get every single interactable in the game activated (due to bugs or glitches or intentional/unintentional design by the developers). So I decided that the Analyzer will feature only things that are currently verified. The list of interactables will be still visible in the Console tab, for anyone who wants to look at it.

I'm closing this, since Geo Rocks are now fully visible in the Geo Caches tab since v2.0.0 👍
Grubs, all Relics, Rancid Eggs, Geo Chests and others are also available now.

I have currently no plans to implement a map. I may consider this if I get enough requests and support.
